# 策略名
strategy_name = "simple_bolling"
# 账户名
account_id = 1
# 交易币种
symbol = 'BTC-USDT_15m'
# btc是0.01，不同的币种要进行不同的替换
face_value = 0.01
# 手续费，commission fees，默认为万分之5。不同市场手续费的收取方法不同，对结果有影响。比如和股票就不一样。
c_rate = 0.0005
# 滑点 ，可以用百分比，也可以用固定值。建议币圈用百分比，股票用固定值
slippage = 0.001
# 杠杆比率
leverage_rate = 3
# 最低保证金率，低于就会爆仓
min_margin_ratio = 0.01
# k线种类
rule_type = '15T'
# 币种刚刚上线10天内不交易
drop_days = 10